Repository milieuinfo/webcomponent-vl-ui-demo, pull requests merged in 2020-06, with the labels that each got.

#7 Introductie vl-ui-demo en ESlint
  .eslintrc.json
  index.js
  package.json
  src/index.js
  src/vl-demo-all.js
  src/vl-demo-page.js
  src/vl-demo.js
  test/e2e/components/vl-demo-page.js
  test/e2e/components/vl-demo.js
  test/e2e/demo.test.js
  test/e2e/pages/vl-demo.page.js
  test/unit/vl-demo-page.test.html
  test/unit/vl-demo.test.html
Labels: chore

#8 Import sinon uit node_modules voor de unit testen
  demo/demo.js
  package-lock.json
  test/unit/vl-demo-page.test.html
  test/unit/vl-demo.test.html
Labels: bugfix

#9 Stijlverbetering door introductie CSS container
  src/vl-demo.js
Labels: bug

#11 Ondersteuning om de vl-header en vl-footer niet te tonen via request parameters
  src/vl-demo-page.js
  test/unit/vl-demo-page.test.html
Labels: enhancement

#12 Update vl-ui-util dependency
  package.json
  src/vl-demo-page.js
  test/unit/vl-demo-page.test.html
Labels: chore

#15 Deduplicatie NPM run scripts Update naar latest vl-ui-util en vl-ui-core
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore
