Repository milieuinfo/webcomponent-vl-ui-demo, pull requests merged in 2020-08, with the labels that each got.

#20 Update dependency prismjs to v1.21.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#21 Introductie vl-ui-code-preview
  demo/vl-demo.html
  dist/style.css
  dist/style.css.map
  dist/style.scss
  dist/vl-demo-all.js
  dist/vl-demo-all.min.js
  dist/vl-demo-all.src.js
  dist/vl-demo-page.js
  dist/vl-demo-page.min.js
  dist/vl-demo-page.src.js
  dist/vl-demo.js
  dist/vl-demo.min.js
  dist/vl-demo.src.js
  package-lock.json
  package.json
  src/style.css
  src/style.css.map
  src/style.scss
  src/vl-demo-all.js
  src/vl-demo-page.js
  src/vl-demo.js
  test/e2e/components/vl-demo.js
  test/e2e/demo.test.js
  test/unit/vl-demo-page.test.html
  test/unit/vl-demo.test.html
Labels: bug, chore

#23 Introductie size attributen
  src/vl-demo-page.js
  test/unit/vl-demo-page.test.html
Labels: enhancement

#25 Update dependencies
  demo/vl-demo.html
  package-lock.json
  package.json
Labels: chore

#26 Demo code preview moet geen focus krijgen bij tab
  src/vl-demo.js
  test/unit/vl-demo.test.html
Labels: chore
